.TH osg-cert-revoke 1 "MARCH 2013" OSG PKI-CLI

.SH NAME
osg-cert-revoke \- To revoke a host certificate.

.SH DESCRIPTION
For description and usage, please refer to,
https://twiki.grid.iu.edu/bin/view/Operations/OSGPKICommandlineClients

.SH OPTIONS
.IP  "-h, --help"            
show this help message and exit
.IP  "-m REASON, --message=REASON"
Specify the reason for certificate revocation.
.IP  "-i Request ID, --id=Request ID"
Specify ID# of host certificate to be revoked
to be revoked
.IP  "-k PKEY, --pkey=PKEY"
Specify Requestor's private key (PEM Format).  If not specified will 
take the value of X509_USER_KEY or $HOME/.globus/userkey.pem
.IP "-c CERT, --cert=CERT"  
Specify Requestor's certificate (PEM Format).  If not specified will 
take the value of X509_USER_CERT or $HOME/.globus/usercert.pem
.IP  "-T, --test"
Run in test mode
.IP  "-q, --quiet"           
don't print status messages to stdout
.IP  "-V, --version"         
Print the script version number and exit. 

.SH AUTHOR
Viplav Khadke