#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
This script is used to retrieve certificates. This script requires no
authentication. It will check the status of the request and request
issuance of the certificate if needed (i.e. it is in the APPROVED
state), wait for that issuance to complete, and then retrieve the
certificate.

Not that between requesting a certificate and retrieving it, it is
required for a registration authority to approve the certificate
through the webUI.

This script checks to see if the output file exists and prompts the
user if it does.
"""

import urllib
import httplib
import sys
import ConfigParser
from optparse import OptionParser
try:
    import json
except ImportError:
    import simplejson as json
import time
import re
import os
import textwrap
import traceback

# Set up Option Parser
#

def charlimit_textwrap(string):
    """This function wraps up tht output to 80 characters. Accepts string and print the wrapped output"""
    list_string = textwrap.wrap(string)
    for line in list_string:
        print line
    return

def parse_args():
    """This function parses all the arguments, validates them and then stores them in a dictionary that is used throughout the script.\n"""
    usage = \
        'usage: %prog [options] arg\nUsage:%prog -h/--help [for detailed explanations of options]'
    parser = OptionParser(usage)
    parser.add_option(
        '-i',
        '--id',
        action='store',
        dest='id',
        help='Specify ID# of certificate to retrieve[Required]',
        metavar='ID',
        )
    parser.add_option(
        '-o',
        '--certfile',
        action='store',
        dest='certfile',
        help='Specify the output filename for the retrieved user certificate\n. Default is ./hostcert.pem'
            ,
        metavar='ID',
        default='./hostcert.pem',
        )
    parser.add_option(
        '-T',
        '--test',
        action='store_true',
        dest='test',
        help='Run in test mode',
        default=False,
        )
    parser.add_option(
        '-q',
        '--quiet',
        action='store_false',
        dest='verbose',
        default=True,
        help="don't print status messages to stdout",
        )

    (args, values) = parser.parse_args()

    if not args.id:
        parser.error('-i/--id argument required')

    reqid = args.id

    if os.path.exists(args.certfile):
        opt = \
            raw_input('The file %s already exists. Do you want to overwrite it? Y/N : \n'
                       % args.certfile)
        if opt == 'y' or opt == 'Y':
            pem_filename = args.certfile
        elif opt == 'n' or opt == 'N':
            pem_filename = \
                raw_input('Please enter a different file name\n')
        else:
            sys.exit('Invalid option')
    else:
        pem_filename = args.certfile
    Config = ConfigParser.ConfigParser()
    if os.path.exists('pki-clients.ini'):
        Config.read('pki-clients.ini')
    elif os.path.exists('/etc/osg/pki-clients.ini'):
        Config.read('/etc/osg/pki-clients.ini')
    else:
        sys.exit('Missing config file: pki-clients.ini\n')
    if args.test:
        print "Running in test mode"
        OIM='OIMData_ITB'
    else:
        OIM='OIMData'
    host = Config.get(OIM, 'host')
    requrl = Config.get(OIM, 'returl')
    appurl = Config.get(OIM, 'appurl')
    issurl = Config.get(OIM, 'issurl')
    content_type = Config.get(OIM, 'content_type')
    filetype = 'hostcert'
    fileext = 'pkcs7'
    filename = '%s.%s.%s' % (filetype, reqid, fileext)

    arguments = dict()
    if vars().has_key('args'):
        arguments.update({'args': args})
    if vars().has_key('values'):
        arguments.update({'values': values})

    if vars().has_key('pem_filename'):
        arguments.update({'pem_filename': pem_filename})
    arguments.update({'id': reqid})
    arguments.update({'filetype': filetype})
    arguments.update({'fileext': fileext})
    arguments.update({'filename': filename})
    arguments.update({'host': host})
    arguments.update({'requrl': requrl})
    arguments.update({'appurl': appurl})
    arguments.update({'content_type': content_type})
    arguments.update({'Config': Config})
    arguments.update({'issurl': issurl})
    return arguments


# Build the connection to the web server - the request header, the parameters
# needed and then pass them into the server
#
# The data returned is in JSON format so to make it a little more human
# readable we pass it through the json module to pretty print it
#
# A WHILE loop exists to keep trying to retrieve the certificate if there
# is a delay in issuing
#
# Then we use a regexp to fix the munged up new lines that get returned
# and put the cert into the proper format, clipping of the extraneous
# JSON formatting and write the certificate file out
#

def connect_issue(arguments):
    """This function accepts a dictionary of parameters and issues the request if the requets is in Approved state."""
    params = urllib.urlencode({'host_request_id': arguments['id']})
    headers = {'Content-type': arguments['content_type'],
               'User-Agent': 'OIMGridAPIClient/0.1 (OIM Grid API)'}
    print 'Contacting Server to initiate certificate issuance. Please wait\n'
    newrequrl = arguments['Config'].get('OIMData', 'issurl')
    conn = httplib.HTTPConnection(arguments['host'])
    try:
        conn.request('POST', newrequrl, params, headers)
        time.sleep(10)
        response = conn.getresponse()
    except Exception, e:
        charlimit_textwrap('Connection to %s failed: %s' % (newrequrl, e))
        raise e
    data = response.read()
    conn.close()
    if not 'OK' in data:
        charlimit_textwrap('''The request failed for the following reason
 %s

''' \
            % json.loads(data)['detail'])
        sys.exit(1)

    return


# Here's where things have gotten dicey during the testing phase -
# We retrieve the certificate from OIM after it has retrieved it from the CA
# This is where things tend to fall apart - if the delay is to long and the
# request to the CA times out, the whole script operation fails. I'm not
# terribly pleased with that at the moment, but it is out of my hands since
# a GOC staffer has to reset the request to be able to retrieve the
# certificate
#

def connect_retrieve(arguments):
    """This function checks if the request is in Issues state.\nIf its is in the issued state, it then retrieves the certificate.\nIt accepts a dictionary that consist of all the parameters and tehir value."""
    iterations = 1
    print 'Connecting server to retrieve certificate...'
    params = urllib.urlencode({'host_request_id': arguments['id']})
    headers = {'Content-type': arguments['content_type'],
               'User-Agent': 'OIMGridAPIClient/0.1 (OIM Grid API)'}
    conn = httplib.HTTPConnection(arguments['host'])
    try:
        conn.request('POST', arguments['requrl'], params, headers)
        response = conn.getresponse()
    except httplib.HTTPException, e:
        charlimit_textwrap('Connection to %s failed: %s' % (newurl, e))
        raise httplib.HTTPException
    data = response.read()
    if json.loads(data).has_key('request_status'):
        if json.loads(data)['request_status'] == 'REQUESTED':
            charlimit_textwrap('Certificate request in Requested state.Needs to be Approved first. Please contact RA to approve this certificate\n'
                     )
            sys.exit(1)
        else:
            charlimit_textwrap('Certificate request in Approved state. Needs to be issued first\n')
            connect_issue(arguments)
    try:
        conn.request('POST', arguments['requrl'], params, headers)
        response = conn.getresponse()
    except httplib.HTTPException, e:
        charlimit_textwrap('Connection to %s failed: %s' % (newurl, e))
        raise httplib.HTTPException
    data = response.read()

    while 'PENDING' in data:
        conn.request('POST', arguments['requrl'], params, headers)
        try:
            response = conn.getresponse()
        except httplib.HTTPException, e:
            charlimit_textwrap('Connection to %s failed: %s' % (newurl, e))
            raise httplib.HTTPException
        data = response.read()
        conn.close()
        if 'PENDING' in data:
            time.sleep(5)
            iterations = iterations + 1
            if iterations % 6 == 0:
                charlimit_textwrap('Waiting for response from Certificate Authority. Please wait.')
                charlimit_textwrap(' Delay: %s minutes'% float(iterations / 12))
            if iterations > 60:
                charlimit_textwrap('Maximum number of attempts reached. This script will now exit.')
                sys.exit(1)
        else:
            pass
    pkcs7raw = json.dumps(json.loads(data), sort_keys=True, indent=2)
    if 'FAILED' in data:
        charlimit_textwrap('''The request failed for the following reason
 %s

''' \
            % json.loads(data)['detail'])
        sys.exit(1)

    # The slice and dice on the JSON output to get the certificate out
    # happens here - the problem is that the new lines are getting all screwy
    # in the output from OIM. We stringify the data, replace all the text
    # newline characters with actual new lines and the strip off the
    # extra data. There's probably a more efficient way to do this, but this
    # was the quick and dirty solution.
    #

    pkcs7raw = str(pkcs7raw)
    pkcs7raw = re.sub('\\\\n', '\n', pkcs7raw)
    pkcs7raw = pkcs7raw.split('[')[1]
    pkcs7raw = pkcs7raw.split('"')[1]
    temp_filename = '%s.%s.%s' % (arguments['filetype'], arguments['id'
                                  ], arguments['fileext'])

    try:
        certfile = open(temp_filename, 'w+')
        certfile.write(pkcs7raw)
        certfile.close()
        os.system('openssl pkcs7 -print_certs -in ' + temp_filename
                  + ' -out ' + arguments['pem_filename'])
        os.chmod(arguments['pem_filename'],0644)
        os.remove(temp_filename)
    except OSError, e:
        charlimit_textwrap('You may not have permission to write on the file system. \nPlease report the bug to goc@opensciencegrid.org.'
                 )
        sys.exit(1)
    charlimit_textwrap('Certificate written to %s \n' % arguments['pem_filename'])
    return


if __name__ == '__main__':
    try:
        os.umask(177)
        try:
            arguments = parse_args()
        except EOFError, e:
            charlimit_textwrap('End of File Error: Check if the standard input is enabled\nError %s'
                  % e)
            sys.exit(1)
        connect_retrieve(arguments)
    except SystemExit, e:
            raise
    except KeyboardInterrupt, k:
        charlimit_textwrap(k)
        sys.exit('''Interrupted by user\n''')
    except Exception, e:
        print traceback.format_exc()
        charlimit_textwrap('''Uncaught Exception : 
Please report the bug to goc@opensciencegrid.org.
'''
                     )
        sys.exit(1)
    sys.exit(0)
