name: Build and Push Docker image

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        yum_repo: ['development', 'testing', 'release']
        osg_series: ['3.6']
    steps:
      - uses: opensciencegrid/build-container-action@v0.3.1
        with:
          osg_series: ${{ matrix.osg_series }}
          repo: ${{ matrix.yum_repo }}

  push:
    runs-on: ubuntu-latest
    if: >-
      github.ref == 'refs/heads/master' &&
      github.event_name != 'pull_request' &&
      github.repository_owner == 'opensciencegrid'
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        yum_repo: ['development', 'testing', 'release']
        osg_series: ['3.6']
        registry:
          - url: hub.opensciencegrid.org
            username: OSG_HARBOR_ROBOT_USER
            password: OSG_HARBOR_ROBOT_PASSWORD
          - url: docker.io
            username: DOCKER_USERNAME
            password: DOCKER_PASSWORD
    steps:
      - uses: opensciencegrid/push-container-action@v0.6.1
        with:
          repo: ${{ matrix.yum_repo}}
          osg_series: ${{ matrix.osg_series }}
          name: '${{ github.repository_owner }}/pki-tools'
          registry_url: ${{ matrix.registry.url }}
          registry_user: ${{ secrets[matrix.registry.username] }}
          registry_pass: ${{ secrets[matrix.registry.password] }}
